version: 2.0

jobs:
  workspace-full:
    docker:
      - image: csweichel/dazzle:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./.circleci/dazzle_build_image.sh full/Dockerfile gitpod/workspace-full workspace-full.tar
          no_output_timeout: 30m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/dazzle/
            cp full/*.xml ~/test-results/dazzle
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/dazzle
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full.tar

  workspace-full-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh full-vnc/Dockerfile gitpod/workspace-full-vnc
            docker save gitpod/workspace-full-vnc -o workspace-full-vnc.tar
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full-vnc.tar

  mdbook:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh mdbook/Dockerfile gitpod/mdbook
          no_output_timeout: 30m

  workspace-dotnet:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh dotnet/Dockerfile gitpod/workspace-dotnet
          no_output_timeout: 60m

  workspace-dotnet-vnc:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full-vnc.tar
            ./.circleci/build_image.sh dotnet-vnc/Dockerfile gitpod/workspace-dotnet-vnc
          no_output_timeout: 30m

  workspace-postgres:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh postgres/Dockerfile gitpod/workspace-postgres
          no_output_timeout: 30m

  workspace-mysql:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh mysql/Dockerfile gitpod/workspace-mysql
          no_output_timeout: 30m

  workspace-mongodb:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh mongodb/Dockerfile gitpod/workspace-mongodb

  workspace-flutter:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh flutter/Dockerfile gitpod/workspace-flutter

  workspace-gecko:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full-vnc.tar
            ./.circleci/build_image.sh gecko/Dockerfile gitpod/workspace-gecko
          no_output_timeout: 60m

  workspace-wasm:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i workspace-full.tar
            ./.circleci/build_image.sh wasm/Dockerfile gitpod/workspace-wasm

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - workspace-full
      - workspace-full-vnc:
          requires:
            - workspace-full
      - mdbook:
          requires:
            - workspace-full
      - workspace-dotnet:
          requires:
            - workspace-full
      - workspace-dotnet-vnc:
          requires:
            - workspace-full-vnc
      - workspace-postgres:
          requires:
            - workspace-full
      - workspace-mysql:
          requires:
            - workspace-full
      - workspace-mongodb:
          requires:
              - workspace-full
      - workspace-flutter:
          requires:
              - workspace-full
      - workspace-gecko:
          requires:
            - workspace-full-vnc
      - workspace-wasm:
          requires:
              - workspace-full
